version: "3"
services:
  gophish:
    image: gophish/gophish:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      GOPHISH_INITIAL_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 8443:8443
      - 8080:8080
      - 172.17.0.1:51766:3333
    volumes:
      - data:/opt/gophish

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
